compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_CPU
downcast_bf16: 'no'
ipex_config:
  ipex: false
machine_rank: 0
main_process_ip: 10.1.8.11
main_process_port: 12345
main_training_function: main
mixed_precision: 'no'
num_machines: 40
num_processes: 1 
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true
